import = ["/Users/adrianeduardotrevinopena/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
live_config_reload = true


[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[shell]
program = "/bin/bash"

[window]
opacity = 0.85
